name: bismillahcapston
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  camera: ^0.10.3+2
  http: ^0.13.5
  shared_preferences: ^2.1.0
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  sliver_bar_chart: ^0.0.1
  flutter_charts: ^0.5.1
  flutter_expandable_fab: ^1.7.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  device_apps: ^2.2.0
  app_launcher: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
